package day8

import (
	"fmt"
	"os"
	"testing"
)

const example = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`

const example2 = `T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........`

func TestCountAntiNodesExample(t *testing.T) {
	input := Parse(example)

	count := CountAntiNodes(input)

	if count != 14 {
		t.Fatalf("expected = 14, got = %v\n", count)
	}

	count2 := CountAntiNodesWithResonance(input)

	if count2 != 34 {
		t.Fatalf("expected = 34, got = %v\n", count2)
	}
}

func TestCountAntiNodes(t *testing.T) {
	inputTxt, err := os.ReadFile("./input.txt")
	if err != nil {
		t.Fatalf("Could not read puzzle input: err = %s", err)
	}

	input := Parse(string(inputTxt))
	count := CountAntiNodes(input)
	count2 := CountAntiNodesWithResonance(input)

	fmt.Printf("# Puzzle\nCount = %v\n\n#Puzzle Part 2\nCount = %v\n", count, count2)
}
